export const eqBands = [
  {
    id: "eq-63hz",
    frequency: 63,
    label: "Sub Weight",
    labelZh: "超低頻／身體感",
    labelEn: "Sub Weight / Feel",
    impression: "超低頻的重量與舞台震動感，常影響 kick、bass 與整體低頻地基。",
    commonProblem: "過多時容易轟、糊，讓 PA 與舞台低頻失控；過少時聲音缺乏重量。",
    commonTreatment: "先確認音箱與舞台共振，再用 low shelf 或 low cut 管理低頻能量。",
    boostSuggestion: "少量提升可增加重量，但需要留意 headroom 與場地共振。",
    cutSuggestion: "若低頻拖尾或舞台轟鳴，可用 low shelf 或 low cut 收斂。",
    boostAdvice: "少量提升可增加重量，但需要留意 headroom 與場地共振。",
    cutAdvice: "若低頻拖尾或舞台轟鳴，可用 low shelf 或 low cut 收斂。",
    phonetic: "",
    phoneticZh: "",
    bodyReference: "Abdomen／腹部震動",
    bodyLabel: "Abdomen",
    memoryHint: "感覺像腹部被低頻推動，是身體先感受到的頻段。",
    curveType: "lowShelf",
    filterType: "lowShelf",
    filterName: "Low Shelf",
    filterDescription: "移除不必要的超低頻，保留可用的低頻重量。",
    filterUseCases: ["舞台隆隆聲", "麥克風低頻震動", "低頻 headroom 管理", "PA 共振"],
    recommendedQ: "0.7 ~ 1.0",
    q: 0.7,
    qCategory: "Wide Q / 寬 Q",
    qDescription: "適合寬範圍的低頻能量控制與自然音色修飾。",
    qApplications: ["Broad tone shaping", "Low-end control", "Natural correction"],
    boostReason: "增加重量",
    cutReason: "減少轟鳴",
    boostIcon: "⬆",
    cutIcon: "⬇",
    gain: 4,
    gainDb: 4,
    color: "#38bdf8",
    instruments: ["Kick", "Bass", "Floor Tom", "Playback"]
  },
  {
    id: "eq-125hz",
    frequency: 125,
    label: "Warmth",
    labelZh: "低頻厚度／胸腔",
    labelEn: "Warmth / Chest",
    impression: "低頻厚度與胸腔共鳴，決定聲音是否溫暖、有身體感。",
    commonProblem: "過多時混音變厚重、不清楚；過少時聲音偏薄、缺乏支撐。",
    commonTreatment: "用寬 Q 輕微調整厚度，避免多個聲源在同一區域累積。",
    boostSuggestion: "可增加人聲、Bass、鼓組的身體感，但不要讓低頻堆積。",
    cutSuggestion: "混音混濁時可小幅削減，讓 kick 與 bass 的低頻輪廓更乾淨。",
    boostAdvice: "可增加人聲、Bass、鼓組的身體感，但不要讓低頻堆積。",
    cutAdvice: "混音混濁時可小幅削減，讓 kick 與 bass 的低頻輪廓更乾淨。",
    phonetic: "",
    phoneticZh: "",
    bodyReference: "Chest／胸腔共鳴",
    bodyLabel: "Chest",
    memoryHint: "像胸口共鳴的厚度，是聲音有身體感的地方。",
    curveType: "bell",
    filterType: "bell",
    filterName: "Low Shelf",
    filterDescription: "用寬廣的方式調整低頻厚度，不只處理單一共振點。",
    filterUseCases: ["胸腔厚度", "Bass 身體感", "鼓組重量", "整體暖度"],
    recommendedQ: "0.7 ~ 1.2",
    q: 1.0,
    qCategory: "Wide Q / 寬 Q",
    qDescription: "適合大範圍調整溫暖感，不容易造成突兀的頻段凸起。",
    qApplications: ["Warmth shaping", "Broad correction", "Tone balance"],
    boostReason: "增加厚度",
    cutReason: "減少混濁",
    boostIcon: "⬆",
    cutIcon: "⬇",
    gain: 3,
    gainDb: 3,
    color: "#22d3ee",
    instruments: ["Vocal", "Bass", "Guitar", "Snare", "Keyboard"]
  },
  {
    id: "eq-250hz",
    frequency: 250,
    label: "Boxiness",
    labelZh: "箱音／混濁",
    labelEn: "Boxiness / Mud",
    impression: "木箱、鼓腔與房間感常聚集的區域。",
    commonProblem: "過多時像悶在箱子裡，聲音變鈍，細節不容易往前。",
    commonTreatment: "用 bell filter 搭配中等 Q 小幅削減，清出中低頻空間。",
    boostSuggestion: "需要增加木質感或低中頻實體時可少量提升。",
    cutSuggestion: "箱音、悶感明顯時可削減，讓聲音更乾淨、更開放。",
    boostAdvice: "需要增加木質感或低中頻實體時可少量提升。",
    cutAdvice: "箱音、悶感明顯時可削減，讓聲音更乾淨、更開放。",
    phonetic: "OO",
    phoneticZh: "烏",
    bodyReference: "Mouth／OO vowel",
    bodyLabel: "OO",
    memoryHint: "像發「烏」時嘴型靠後、聲音偏圓的區域。",
    curveType: "bell",
    filterType: "bell",
    filterName: "Bell (Peak)",
    filterDescription: "局部修正箱音、混濁或突出的低中頻。",
    filterUseCases: ["箱音", "混濁", "低中頻堆積", "鼓腔共振"],
    recommendedQ: "1.5 ~ 2.5",
    q: 2.0,
    qCategory: "Medium Q / 中等 Q",
    qDescription: "適合一般音色修飾與局部問題控制。",
    qApplications: ["General EQ", "Tone shaping", "Problem control"],
    boostReason: "增加木質感",
    cutReason: "減少箱音",
    boostIcon: "⬆",
    cutIcon: "⬇",
    gain: -6,
    gainDb: -6,
    color: "#4ade80",
    instruments: ["Acoustic Guitar", "Snare", "Tom", "Vocal", "Piano"]
  },
  {
    id: "eq-500hz",
    frequency: 500,
    label: "Honk / Mud",
    labelZh: "鼻音／悶",
    labelEn: "Honk / Mud",
    impression: "中低頻悶感、鼻音與聲音前後距離感的關鍵區域。",
    commonProblem: "過多時人聲或樂器容易鼻、悶、缺乏開放感。",
    commonTreatment: "用 bell filter 找出悶點，小幅削減即可，避免挖空主體。",
    boostSuggestion: "少量提升可讓聲音更靠前，但很容易變鼻或悶。",
    cutSuggestion: "悶、糊、鼻音重時可削減，讓聲音輪廓更清楚。",
    boostAdvice: "少量提升可讓聲音更靠前，但很容易變鼻或悶。",
    cutAdvice: "悶、糊、鼻音重時可削減，讓聲音輪廓更清楚。",
    phonetic: "O",
    phoneticZh: "喔",
    bodyReference: "Mouth／O vowel",
    bodyLabel: "O",
    memoryHint: "像發「喔」時的口腔共鳴，容易聽成悶或鼻。",
    curveType: "bell",
    filterType: "bell",
    filterName: "Bell (Peak)",
    filterDescription: "針對悶、鼻或中低頻突起做局部修正。",
    filterUseCases: ["鼻音", "悶感", "口腔共鳴", "中低頻遮蔽"],
    recommendedQ: "1.2 ~ 2.0",
    q: 1.6,
    qCategory: "Medium Q / 中等 Q",
    qDescription: "適合控制中低頻混濁與鼻音，同時保留自然過渡。",
    qApplications: ["Mud control", "Honk reduction", "Tone shaping"],
    boostReason: "增加中頻實體",
    cutReason: "降低鼻音",
    boostIcon: "⬆",
    cutIcon: "⬇",
    gain: -4,
    gainDb: -4,
    color: "#a3e635",
    instruments: ["Vocal", "Saxophone", "Guitar", "Snare", "Tom"]
  },
  {
    id: "eq-1khz",
    frequency: 1000,
    label: "Presence Core",
    labelZh: "中頻存在／箱感",
    labelEn: "Presence / Boxy",
    impression: "聲音的核心存在感，決定樂器是否站得住。",
    commonProblem: "過多時容易硬、擠；過少時聲音退後、不容易辨識。",
    commonTreatment: "以寬 Q 做小幅調整，讓聲源保持存在感但不刺耳。",
    boostSuggestion: "可增加語音與樂器的可辨識度，但過量會讓混音擁擠。",
    cutSuggestion: "聲音硬、擠、壓迫時可小幅削減。",
    boostAdvice: "可增加語音與樂器的可辨識度，但過量會讓混音擁擠。",
    cutAdvice: "聲音硬、擠、壓迫時可小幅削減。",
    phonetic: "AH",
    phoneticZh: "啊",
    bodyReference: "Throat／喉嚨／中頻",
    bodyLabel: "Throat",
    memoryHint: "像發「啊」的母音，是中頻存在感的核心。",
    curveType: "bell",
    filterType: "bell",
    filterName: "Bell (Peak)",
    filterDescription: "控制中頻核心存在感，讓聲音站得住但不擁擠。",
    filterUseCases: ["中頻存在", "箱感", "聲音靠前", "硬感"],
    recommendedQ: "1.0 ~ 1.8",
    q: 1.2,
    qCategory: "Medium Q / 中等 Q",
    qDescription: "適合調整存在感核心，讓聲音更靠前或更柔和。",
    qApplications: ["Presence shaping", "Midrange focus", "Vocal control"],
    boostReason: "增加存在感",
    cutReason: "減少壓迫感",
    boostIcon: "⬆",
    cutIcon: "⬇",
    gain: 2,
    gainDb: 2,
    color: "#facc15",
    instruments: ["Vocal", "Guitar", "Keyboard", "Snare", "Brass"]
  },
  {
    id: "eq-2khz",
    frequency: 2000,
    label: "Attack",
    labelZh: "咬字／攻擊",
    labelEn: "Attack / Bite",
    impression: "語音清楚度、撥弦攻擊與鼓件擊點感的區域。",
    commonProblem: "過多時刺耳、疲勞；過少時咬字不清、攻擊感不足。",
    commonTreatment: "用中等 Q 控制攻擊感，讓聲音清楚但不要尖銳。",
    boostSuggestion: "可增加咬字、擊點與存在感，適合需要往前的聲源。",
    cutSuggestion: "刺耳、疲勞或太衝時可小幅削減。",
    boostAdvice: "可增加咬字、擊點與存在感，適合需要往前的聲源。",
    cutAdvice: "刺耳、疲勞或太衝時可小幅削減。",
    phonetic: "A",
    phoneticZh: "ㄟ／艾",
    bodyReference: "Mouth／A vowel",
    bodyLabel: "A",
    memoryHint: "像發「ㄟ／艾」時較前面的口腔亮度與攻擊感。",
    curveType: "bell",
    filterType: "bell",
    filterName: "Bell (Peak)",
    filterDescription: "調整咬字與攻擊感，避免聲音太衝或不清楚。",
    filterUseCases: ["咬字", "攻擊", "擊點", "存在感"],
    recommendedQ: "1.2 ~ 2.0",
    q: 1.4,
    qCategory: "Medium Q / 中等 Q",
    qDescription: "適合控制 attack 與咬字清晰度，避免影響過寬頻段。",
    qApplications: ["Attack control", "Clarity shaping", "Bite adjustment"],
    boostReason: "增加攻擊感",
    cutReason: "降低刺耳",
    boostIcon: "⬆",
    cutIcon: "⬇",
    gain: 3,
    gainDb: 3,
    color: "#fb923c",
    instruments: ["Vocal", "Guitar", "Snare", "Kick", "Percussion"]
  },
  {
    id: "eq-4khz",
    frequency: 4000,
    label: "Edge",
    labelZh: "刺耳／清晰",
    labelEn: "Edge / Clarity",
    impression: "清晰度、存在感與刺耳感的交界。",
    commonProblem: "過多時刺、尖、容易造成聽覺疲勞；過少時細節不明。",
    commonTreatment: "用較窄 Q 找刺耳點，必要時小幅削減。",
    boostSuggestion: "可增加清晰度與輪廓，但很容易變刺。",
    cutSuggestion: "刺耳、刮耳、過度攻擊時可削減。",
    boostAdvice: "可增加清晰度與輪廓，但很容易變刺。",
    cutAdvice: "刺耳、刮耳、過度攻擊時可削減。",
    phonetic: "EE",
    phoneticZh: "衣",
    bodyReference: "Teeth／EE vowel",
    bodyLabel: "EE",
    memoryHint: "像發「衣」時靠前、偏亮、容易刺的聲音。",
    curveType: "bell",
    filterType: "bell",
    filterName: "Bell (Peak)",
    filterDescription: "針對刺耳、清晰度或局部共振做精準修正。",
    filterUseCases: ["刺耳", "清晰度", "齒邊感", "局部共振"],
    recommendedQ: "1.8 ~ 3.0",
    q: 2.2,
    qCategory: "Narrow Q / 窄 Q",
    qDescription: "適合針對較集中的刺耳感或邊緣感做精準控制。",
    qApplications: ["Harshness control", "Focused cuts", "Edge shaping"],
    boostReason: "增加清晰度",
    cutReason: "降低刺耳",
    boostIcon: "⬆",
    cutIcon: "⬇",
    gain: -3,
    gainDb: -3,
    color: "#f97316",
    instruments: ["Vocal", "Cymbal", "Guitar", "Snare", "Brass"]
  },
  {
    id: "eq-8khz",
    frequency: 8000,
    label: "Brightness",
    labelZh: "齒音／明亮",
    labelEn: "Brightness / Sibilance",
    impression: "高頻亮度、細節與空間邊緣感。",
    commonProblem: "過多時嘶、沙、齒音明顯；過少時聲音暗淡。",
    commonTreatment: "依聲源使用 bell 或 high shelf，控制亮度與齒音。",
    boostSuggestion: "可增加空氣與亮度，但要留意齒音與 cymbal 刺耳。",
    cutSuggestion: "齒音、沙聲或高頻疲勞時可削減。",
    boostAdvice: "可增加空氣與亮度，但要留意齒音與 cymbal 刺耳。",
    cutAdvice: "齒音、沙聲或高頻疲勞時可削減。",
    phonetic: "S",
    phoneticZh: "S",
    bodyReference: "Sibilance／齒音",
    bodyLabel: "S",
    memoryHint: "像 S 的氣音與齒音，是高頻亮度和刺耳感的入口。",
    curveType: "bell",
    filterType: "bell",
    filterName: "Bell (Peak)",
    filterDescription: "針對齒音與高頻刺點做局部控制。",
    filterUseCases: ["齒音", "明亮", "沙聲", "高頻刺點"],
    recommendedQ: "2.0 ~ 3.5",
    q: 2.5,
    qCategory: "Narrow Q / 窄 Q",
    qDescription: "適合處理齒音與明亮區域的局部刺激感。",
    qApplications: ["Sibilance control", "Focused correction", "Brightness control"],
    boostReason: "增加亮度",
    cutReason: "降低齒音",
    boostIcon: "⬆",
    cutIcon: "⬇",
    gain: -4,
    gainDb: -4,
    color: "#f43f5e",
    instruments: ["Vocal", "Hi-Hat", "Cymbal", "Acoustic Guitar", "Playback"]
  },
  {
    id: "eq-16khz",
    frequency: 16000,
    label: "Air",
    labelZh: "空氣感／超高頻",
    labelEn: "Air / Ultra High",
    impression: "聲音上方的空氣、開放感與細緻延伸。",
    commonProblem: "過多時噪聲、嘶聲與不自然的亮感會被放大。",
    commonTreatment: "用 high shelf 少量調整空氣感，避免把噪聲一起推上來。",
    boostSuggestion: "可增加開放感、空氣感與精緻度。",
    cutSuggestion: "若高頻噪聲、嘶聲或刺耳感太明顯，可用 shelf 或 high cut 收斂。",
    boostAdvice: "可增加開放感、空氣感與精緻度。",
    cutAdvice: "若高頻噪聲、嘶聲或刺耳感太明顯，可用 shelf 或 high cut 收斂。",
    phonetic: "TS",
    phoneticZh: "TS／ㄘ",
    bodyReference: "Teeth／Air",
    bodyLabel: "TS",
    memoryHint: "像 TS／ㄘ 的氣音尾端，是空氣感與超高頻延伸。",
    curveType: "highShelf",
    filterType: "highShelf",
    filterName: "High Shelf",
    filterDescription: "以寬廣方式調整空氣感與超高頻延伸。",
    filterUseCases: ["空氣感", "超高頻", "開放感", "高頻噪聲控制"],
    recommendedQ: "0.6 ~ 1.0",
    q: 0.8,
    qCategory: "Wide Q / 寬 Q",
    qDescription: "適合大範圍空氣感與超高頻修飾，維持平順延伸。",
    qApplications: ["Air shaping", "Broad high-end lift", "Smooth correction"],
    boostReason: "增加空氣感",
    cutReason: "降低高頻噪聲",
    boostIcon: "⬆",
    cutIcon: "⬇",
    gain: 3,
    gainDb: 3,
    color: "#e879f9",
    instruments: ["Vocal", "Cymbal", "Strings", "Acoustic Guitar", "Playback"]
  }
];

export const boostCutTeaching = {
  title: "Boost vs Cut",
  boostLabel: "Boost",
  cutLabel: "Cut",
  suggestionLabel: "Suggestion",
  reasonLabel: "Reason",
  decisionTitle: "Decision Hint",
  hints: [
    {
      question: "When to boost?",
      answer: "Boost if something is missing.",
      answerZh: "缺少時再提升。"
    },
    {
      question: "When to cut?",
      answer: "Cut if something is excessive.",
      answerZh: "過多時先削減。"
    }
  ],
  priority: "Always cut first if possible.",
  priorityZh: "能 Cut 就先 Cut。"
};
